"project_id_env" : CROWDIN_PROJECT_ID
"api_token_env" : CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy" : true

"files": [
  {
    "source": "/deeds-dapp-webapp/src/main/webapp/static/i18n/messages.properties",   
    "translation": "/deeds-dapp-webapp/src/main/webapp/static/i18n/%file_name%_%two_letters_code%.properties",
    "dest": "/dapp/messages.properties", 
    "type": "properties", 
    "escape_quotes": 0,
    "escape_special_characters": 0
  }
  ,
  {
    "source": "deeds-dapp-webapp/src/main/webapp/static/i18n/tenantPlaceholder.properties",   
    "translation": "/deeds-dapp-webapp/src/main/webapp/static/i18n/%file_name%_%two_letters_code%.properties",
    "dest": "/dapp/tenant.properties", 
    "type": "properties", 
    "escape_quotes": 0,
    "escape_special_characters": 0
  }
  
]
