"project_id_env" : CROWDIN_PROJECT_ID
"api_token_env" : CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy" : true

"files": [
  {
    "source": "/deeds-dapp-webapp/src/main/webapp/static/i18n/messages_en.properties",   
    "translation": "/deeds-dapp-webapp/src/main/webapp/static/i18n/%file_name%_%two_letters_code%.properties",
    "dest": "/dapp/messages.properties", 
    "type": "properties", 
    "translation_replace": {
      "_en": ""
    }    
  }
]
